### ISSUE TITLE
assert ct > 0, 'not found any coco record in %s' % (anno_path)

### ISSUE THREAD

**Issue by DiKu-nn** [FishStalkers/COCO-to-PP-YOLOE-R#1]
i have used your COCO-to-PP-YOLOE-R for coco_datasets, but i have this error:

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 142, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/dinkun/PaddleDetection-develop/ppdet/engine/trainer.py", line 99, in __init__
    self.dataset, cfg.worker_num)
  File "/home/dinkun/PaddleDetection-develop/ppdet/data/reader.py", line 168, in __call__
    self.dataset.parse_dataset()
  File "/home/dinkun/PaddleDetection-develop/ppdet/data/source/coco.py", line 241, in parse_dataset
    assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in /home/Dataset/rot_jzt/annotations/instance_train_4xy_name.json

**Comment by todesti2** [comment]
请问你解决了吗
